version: '3.7'

services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    command: bash -c "npm i; npm run dev"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    command: bash -c "npm i; npm run dev"

networks:
  default:
    name: my-network
