name: Check ESLint on Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Linting Files
        run: npx eslint .
